{"name": "При создании нового заказа счётчик \"Выполнено за сегодня\" увеличивается", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:197:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:527:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16", "trace": "self = <test_order_feed.TestOrderFeed object at 0x000002503F6E5A90>\ndriver = <selenium.webdriver.firefox.webdriver.WebDriver (session=\"fc0ee88e-4074-4604-a478-532054dd8728\")>\n\n    @allure.title('При создании нового заказа счётчик \"Выполнено за сегодня\" увеличивается')\n    def test_creating_order_counter_completed_today_is_incremented(self, driver):\n        test = OrderFeed(driver)\n        test.login()\n        test.click_switch_order_feed()\n>       count = test.get_count_today()\n\ntests\\test_order_feed.py:52: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages\\order_feed_page.py:91: in get_count_today\n    self.wait_to_visibility(LocatorsOrderPage.COUNT_ORDERS_TODAY)\npages\\base_page.py:13: in wait_to_visibility\n    WebDriverWait(self.driver, 10).until(EC.visibility_of_element_located(locator))\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"fc0ee88e-4074-4604-a478-532054dd8728\")>\nmethod = <function visibility_of_element_located.<locals>._predicate at 0x000002503F76D760>, message = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Wait until the method returns a value that is not False.\n    \n        Calls the method provided with the driver as an argument until the\n        return value does not evaluate to ``False``.\n    \n        Parameters:\n        ----------\n        method: callable(WebDriver)\n            - A callable object that takes a WebDriver instance as an argument.\n    \n        message: str\n            - Optional message for :exc:`TimeoutException`\n    \n        Return:\n        -------\n        object: T\n            - The result of the last call to `method`\n    \n        Raises:\n        -------\n        TimeoutException\n            - If 'method' does not return a truthy value within the WebDriverWait\n            object's timeout\n    \n        Example:\n        --------\n        >>> from selenium.webdriver.common.by import By\n        >>> from selenium.webdriver.support.ui import WebDriverWait\n        >>> from selenium.webdriver.support import expected_conditions as EC\n    \n        # Wait until an element is visible on the page\n        >>> wait = WebDriverWait(driver, 10)\n        >>> element = wait.until(EC.visibility_of_element_located((By.ID, \"exampleId\")))\n        >>> print(element.text)\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            if time.monotonic() > end_time:\n                break\n            time.sleep(self._poll)\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nE       WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:197:5\nE       NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:527:5\nE       dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\nvenv\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py:146: TimeoutException"}, "steps": [{"name": "Логиним пользователя", "status": "passed", "steps": [{"name": "Клик по элементу", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: Element <button class=\"button_button__33qZ0 button_button_type_primary__1O7Bx button_button_size_large__G21Vg\"> is not clickable at point (1276,440) because another element <div class=\"Modal_modal_overlay__x2ZCr\"> obscures it\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:197:5\nElementClickInterceptedError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:342:5\nwebdriverClickElement@chrome://remote/content/marionette/interaction.sys.mjs:177:11\ninteraction.clickElement@chrome://remote/content/marionette/interaction.sys.mjs:136:11\nclickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:344:29\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:220:31\n\n", "trace": "  File \"C:\\Users\\appoc\\PycharmProjects\\3prod\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\appoc\\PycharmProjects\\3prod\\pages\\base_page.py\", line 22, in click_element\n    self.driver.find_element(*locator).click()\n  File \"C:\\Users\\appoc\\PycharmProjects\\3prod\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 119, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"C:\\Users\\appoc\\PycharmProjects\\3prod\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 572, in _execute\n    return self._parent.execute(command, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\appoc\\PycharmProjects\\3prod\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\appoc\\PycharmProjects\\3prod\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Ожидаем, что элемент станет кликабельным", "status": "passed", "parameters": [{"name": "locator", "value": "['xpath', \"//button[contains(@class, 'button_button__33qZ0')]\"]"}], "start": 1742133787626, "stop": 1742133787682}], "parameters": [{"name": "locator", "value": "['xpath', \"//button[contains(@class, 'button_button__33qZ0')]\"]"}], "start": 1742133787626, "stop": 1742133787699}, {"name": "Ввод данных", "status": "passed", "parameters": [{"name": "locator", "value": "['xpath', \"//*[text()='Email']/following-sibling::input\"]"}, {"name": "keys", "value": "'qweasdzxc@gmail.com'"}], "start": 1742133787761, "stop": 1742133788090}, {"name": "Ввод данных", "status": "passed", "parameters": [{"name": "locator", "value": "['xpath', \"//*[text()='Пароль']/following-sibling::input\"]"}, {"name": "keys", "value": "'qweasdzxc1233'"}], "start": 1742133788090, "stop": 1742133788142}, {"name": "Клик по элементу", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: Element <button class=\"button_button__33qZ0 button_button_type_primary__1O7Bx button_button_size_medium__3zxIa\"> is not clickable at point (768,549) because another element <div class=\"Modal_modal_overlay__x2ZCr\"> obscures it\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:197:5\nElementClickInterceptedError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:342:5\nwebdriverClickElement@chrome://remote/content/marionette/interaction.sys.mjs:177:11\ninteraction.clickElement@chrome://remote/content/marionette/interaction.sys.mjs:136:11\nclickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:344:29\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:220:31\n\n", "trace": "  File \"C:\\Users\\appoc\\PycharmProjects\\3prod\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\appoc\\PycharmProjects\\3prod\\pages\\base_page.py\", line 22, in click_element\n    self.driver.find_element(*locator).click()\n  File \"C:\\Users\\appoc\\PycharmProjects\\3prod\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 119, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"C:\\Users\\appoc\\PycharmProjects\\3prod\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 572, in _execute\n    return self._parent.execute(command, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\appoc\\PycharmProjects\\3prod\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\appoc\\PycharmProjects\\3prod\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Ожидаем, что элемент станет кликабельным", "status": "passed", "parameters": [{"name": "locator", "value": "['xpath', \"//button[text()='Войти']\"]"}], "start": 1742133788142, "stop": 1742133788162}], "parameters": [{"name": "locator", "value": "['xpath', \"//button[text()='Войти']\"]"}], "start": 1742133788142, "stop": 1742133788173}], "start": 1742133787625, "stop": 1742133788202}, {"name": "Переходим в ленту заказов", "status": "passed", "steps": [{"name": "Клик по элементу", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: Element <a class=\"AppHeader_header__link__3D_hX\" href=\"/feed\"> is not clickable at point (412,44) because another element <div class=\"Modal_modal_overlay__x2ZCr\"> obscures it\nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:197:5\nElementClickInterceptedError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:342:5\nwebdriverClickElement@chrome://remote/content/marionette/interaction.sys.mjs:177:11\ninteraction.clickElement@chrome://remote/content/marionette/interaction.sys.mjs:136:11\nclickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:344:29\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:220:31\n\n", "trace": "  File \"C:\\Users\\appoc\\PycharmProjects\\3prod\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\appoc\\PycharmProjects\\3prod\\pages\\base_page.py\", line 22, in click_element\n    self.driver.find_element(*locator).click()\n  File \"C:\\Users\\appoc\\PycharmProjects\\3prod\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 119, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"C:\\Users\\appoc\\PycharmProjects\\3prod\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 572, in _execute\n    return self._parent.execute(command, params)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\appoc\\PycharmProjects\\3prod\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\appoc\\PycharmProjects\\3prod\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 232, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Ожидаем, что элемент станет кликабельным", "status": "passed", "parameters": [{"name": "locator", "value": "['xpath', '//a[@href=\"/feed\"]']"}], "start": 1742133788203, "stop": 1742133788282}], "parameters": [{"name": "locator", "value": "['xpath', '//a[@href=\"/feed\"]']"}], "start": 1742133788203, "stop": 1742133788298}], "start": 1742133788203, "stop": 1742133788390}, {"name": "Количество заказов за день", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:197:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:527:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n", "trace": "  File \"C:\\Users\\appoc\\PycharmProjects\\3prod\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\appoc\\PycharmProjects\\3prod\\pages\\order_feed_page.py\", line 91, in get_count_today\n    self.wait_to_visibility(LocatorsOrderPage.COUNT_ORDERS_TODAY)\n  File \"C:\\Users\\appoc\\PycharmProjects\\3prod\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\appoc\\PycharmProjects\\3prod\\pages\\base_page.py\", line 13, in wait_to_visibility\n    WebDriverWait(self.driver, 10).until(EC.visibility_of_element_located(locator))\n  File \"C:\\Users\\appoc\\PycharmProjects\\3prod\\venv\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 146, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Ожидаем загрузки элемента", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \nStacktrace:\nRemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:197:5\nNoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:527:5\ndom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16\n\n", "trace": "  File \"C:\\Users\\appoc\\PycharmProjects\\3prod\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n           ^^^^^^^^^^^^^^\n  File \"C:\\Users\\appoc\\PycharmProjects\\3prod\\pages\\base_page.py\", line 13, in wait_to_visibility\n    WebDriverWait(self.driver, 10).until(EC.visibility_of_element_located(locator))\n  File \"C:\\Users\\appoc\\PycharmProjects\\3prod\\venv\\Lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 146, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "parameters": [{"name": "locator", "value": "['xpath', '//*[text() = \"Выполнено за сегодня:\"]/following::*[@class][1]']"}], "start": 1742133788390, "stop": 1742133798964}], "start": 1742133788390, "stop": 1742133798969}], "parameters": [{"name": "driver", "value": "'firefox'"}], "start": 1742133787625, "stop": 1742133798973, "uuid": "bef54000-364c-46bd-af1e-ed3c668b8aed", "historyId": "2bb7ca01a2039b2b4952a83f1ce6dd9e", "testCaseId": "d98f427e74b0bcd25f14e44385a5633b", "fullName": "tests.test_order_feed.TestOrderFeed#test_creating_order_counter_completed_today_is_incremented", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order_feed"}, {"name": "subSuite", "value": "TestOrderFeed"}, {"name": "host", "value": "Pro_Fortis_M"}, {"name": "thread", "value": "31072-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_feed"}]}